--liquibase formatted sql
--changeset martin.b.bach:r1_01 failOnError:true labels:r1

create table "EML_RECIPIENTS" (
   "ID"              number
      generated by default on null as identity,
   "RECIPIENT_EMAIL" varchar2(255) not null enable,
   "CREATED_ON"      date not null enable,
   "CREATED_BY"      varchar2(255) not null enable,
   "UPDATED_ON"      date not null enable,
   "UPDATED_BY"      varchar2(255) not null enable,
   "ROW_VERSION"     number(*,0) not null enable,
   constraint "EML_RECIPIENTS_PK" primary key ( "ID" )
      using index enable
);