--liquibase formatted sql
--changeset martin.b.bach:r1_01 failOnError:true labels:r1

create table em_email_1 (
    id                            number         generated by default on null as identity
                                                 constraint em_email_1_pk primary key,
    recipient_email               varchar2(255)  not null,
    subject                       varchar2(255),
    body                          clob,
    metadata                      json,
    created_on                    date           not null,
    created_by                    varchar2(255)  not null,
    updated_on                    date           not null,
    updated_by                    varchar2(255)  not null,
    row_version                   integer        not null );