--liquibase formatted sql
--changeset martin.b.bach:r1_03 failOnError:true labels:r1

create table "EML_EMAIL_CONTENT" (
   "ID"           number
      generated by default on null as identity,
   "RECIPIENT_ID" number not null enable,
   "METADATA"     json,
   "SUBJECT"      varchar2(255),
   "BODY"         json,
   "CREATED_ON"   date not null enable,
   "CREATED_BY"   varchar2(255) not null enable,
   "UPDATED_ON"   date not null enable,
   "UPDATED_BY"   varchar2(255) not null enable,
   "ROW_VERSION"  number(*,0) not null enable,
   constraint "EML_EMAIL_CONTENT_PK" primary key ( "ID" )
      using index enable
);

alter table "EML_EMAIL_CONTENT"
   add constraint "EML_EMAIL_CONTENT_RECIPIENT_FK"
      foreign key ( "RECIPIENT_ID" )
         references "EML_RECIPIENTS" ( "ID" )
            on delete cascade
      enable;

create index "EMAIL_CONTENT_INDX_1" on
   "EML_EMAIL_CONTENT" (
      "RECIPIENT_ID"
   );