--liquibase formatted sql
--changeset mcb:r1-01 failOnError:true labels:r1

create table demo_thing_categories (
	id         number
		generated by default on null as identity
	not null enable,
	name       varchar2(80),
	constraint demo_thing_categories_id_pk primary key ( id )
		using index enable,
	constraint thing_categories_name_unq unique ( name )
		using index enable
);

-- rollback drop table demo_thing_categories;