---
- name: Automate all the things - DOAG K&A 2026
  hosts: demo
  become: true
  tasks:
    # DBA password must be passed as an extra-variable
    - name: Ensure DBA password is available
      ansible.builtin.fail:
        msg: Make sure to pass the dba_password as an extra variable to the playbook
      when: dba_password is undefined

    - name: Check for Oracle Linux
      ansible.builtin.fail:
        msg: "This playbook requires Oracle Linux 10, this is  {{ ansible_distribution }} {{ ansible_distribution_major_version }}"
      when: ansible_distribution == "OracleLinux" and ansible_distribution_major_version != "10"

    - name: Ensure Intel x86-64
      ansible.builtin.fail:
        msg: "This playbook requires Oracle Linux x86-64, but I found {{ ansible_architecture }}"
      when: ansible_architecture != "x86_64"

    - name: Complete the host configuration
      ansible.builtin.include_role:
        name: hostconfig
      tags: hostconfig

    - name: Install Oracle AI Database 23.26.3 and create a database
      ansible.builtin.include_role:
        name: database
      tags: database

    - name: Install, configure ORDS and enable PDB Lifecycle Management
      ansible.builtin.include_role:
        name: ords
      tags: ords
