--liquibase formatted sql
--changeset mcb:r1-02 failOnError:true labels:r1

create table demo_things (
	id          number
		generated by default on null as identity
	not null enable,
	category    number,
	name        varchar2(80),
	description varchar2(200),
	price       number,
	available   date,
	constraint demo_things_id_pk primary key ( id )
		using index enable
)
/

alter table demo_things
	add constraint demo_things_category_fk foreign key ( category )
		references demo_thing_categories ( id )
	enable
/

create index demo_things_i1 on
    demo_things (
        category
    )
/