--liquibase formatted sql
--changeset mcb:r1-04 failOnError:true labels:r1

create table demo_thing_stock (
	id         number
		generated by default on null as identity not null enable,
	thing_id   number,
	warehouse  number,
	quantity   number,
	constraint demo_thing_stock_id_pk primary key ( id )
)
/

alter table demo_thing_stock
	add constraint demo_thing_stock_thing_id_fk foreign key ( thing_id )
		references demo_things ( id )
			on delete cascade
	enable
/

alter table demo_thing_stock
	add constraint demo_thing_stock_warehouse_fk foreign key ( warehouse )
		references demo_warehouse ( id )
			on delete cascade
	enable
/

create index demo_thing_stock_i2 on
    demo_thing_stock (
        warehouse
    )
/

create index demo_thing_stock_i1 on
    demo_thing_stock (
        thing_id
    )
/