--liquibase formatted sql
--changeset mcb:r1-03 failOnError:true labels:r1

create table demo_warehouse (
	id   number
		generated by default on null as identity
	not null enable,
	name varchar2(80),
	constraint demo_warehouse_id_pk primary key ( id )
		using index enable,
	constraint warehouse_name_unq unique ( name )
		using index enable
);